#!/bin/bash

# rs rs rs

exec_or_debug=$(test "$1" == "-d" && echo echo)
do="$exec_or_debug sudo"

to() {
	f=$1; shift
	$do bash -c "echo $@ > $f"
}

addkey() {
	$do apt-key adv --keyserver keyserver.ubuntu.com \
		--recv-keys $1
}

apt() {
	$do apt-get update
	$do apt-get $@
	$do rm /var/cache/apt/archives/*.deb
}

g-clone() {
	git config --global push.default current
	git config --global user.name 'Elias Gabriel Amaral da Silva'
	git config --global user.email 'tolkiendili@gmail.com'

	git clone git@github.com:dlight/hydra-mud.git ~/e/hydra-mud
	git clone git@github.com:dlight/my-tools.git ~/e/my-tools
}

# --

mkdir -p ~/etc ~/bin ~/e/hydra-mud ~/e/my-tools

$do ntpdate ntp.cais.rnp.br

to /etc/apt/sources.list.d/rs.list \
	deb http://ppa.launchpad.net/chromium-daily/ppa/ubuntu karmic main

to ~/etc/apt-get \
	git-core autoconf \
	manpages-posix-dev \
	vim \
	ucspi-tcp \
	chromium-browser flashplugin-installer \
	mplayer \
	xchat pidgin

addkey 4E5E17B5

apt -y install $(< ~/etc/apt-get)

# arg..

cat > ~/.ssh/known_hosts <<rsrs
|1|e0SnpjtDREuAKayH5AGkr/OTAZs=|rgrpf3x7ed8BSaFSkuYKvw6aARE= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
|1|XPVIWkRz0TOBdGV+dAIAmPt7E+8=|sWmwWBW64jyq5wxIeoNqHIhKjLs= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
rsrs

cat > ~/.ssh/id_rsa <<rsrs
-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: DES-EDE3-CBC,669F8AD73295E75E

44eNQ59J01WEuVJ3dSeIuUYvWzGfc4Am1Azs4YifkpzR8bY+J+y1aFW1rJIIxg4V
Y0TLHX52OQ6hVj370H4CovoKs7/jgG7r8yV3MpcC1zlgr3zqHkinSESpixngONK0
yw1yWG4IVqQNlO3eXggg6wBqokAwgvrGEM83xIn0Ec30gpGMgEzy4PEdT8U182qd
AALfEhGNM59wGfWrgRR7VSjd0eOxvY8PddUo/TIfYC5s+IyQvBmvVRfhc1u89GmN
8QesC/fd0DA+6Dplx5wnLhmuPBKjh3NjzF+UfkuiLIjKvv8UVsNZ3izl0N6uXqg1
WhvNHBbX4XiCVWT9vk0DBLYaW0UFNLYGJWPuQOxELgUQvZSnWa/YoCKlPJeY9yh+
kzy35qig2mTMAqa7h5YP8bjUsqDRIgdGcfcxrxk+2NU2w0vRodKZHN6HB0PHbPP0
qXJ2O6YVv/ziDRSaH3sdSGEB5DsXVg0zgV3p1veVIa1SvXyOi1Fi4VkeAGtgVQ8J
5mKPNtM1kiH4IFBFgi7KBEuawh+nu7cxlvJN96BaZxoo2De1L39wAKow5r4qneI6
Kz0FB6W04oHmNeLU+IxzZ+jsnssEsKUqhjM2M/VgcCchx62ukYPTnNwjXRa3SyzG
OSEb4RkA8HkVY4SNgMVQmqG/Dfyd2QTvQe5CKsxWSWJyKSrg8/IOopkP7T4AtX09
7NF5uMRyo1g2IId0nJnZYc+PA4Bzs67R+DWTrmXOOEgMFj08O1syPr1CLJybwj0L
kohyXLjvuWxHI3Qpw04zsugwS1sPsUnPXh9uP+vaheTwftejnrvB9pY5ciw/nLez
MfIcNdcjvfxhFk7lhDOMDsxnacZSi3E5wLXYWx0gkQ+3WJ+EQxlQXUKNy4fqRTxK
Kvkuw+sDS27IJP11dvOFNbTrfIt9FKu66kTZxc1/s18aOwwuBJjj0MI6rmQkj+55
yMS8Bto3yV98YfMWi3q57F6048cnK5wMUt8ne0Poe7amnP5o8vd2zXQbMflvUp9P
s8NexCHeMzYxd2fFA1f/Ayvc2XUuNjZ7TA3rWGQjpUujs3NYvnggopw7Noe10BeF
Y7y3tWfAjLiZjkbTvIEV6IqficFHQPqNpY0Dyoo7mNKxNmRqTVw+abTfqqt1RtG3
71feiDoKiX5c8k1UyS6HtZc+tQeLsVJyOG/Jpt8edyIFf9U28Ys58QSKxTrDIxtZ
9WrbHxk6Dzru9RO4qXjTERB/zo/kvAA5AY4+sVEgJ8V5VfHtBNyPdJqUqxBS4Hup
EJ5UBwZJUzo/k7wo5d5UnEDZc8gvmDbm7hhLvAv6ADurZrWLxBWEbMBXzNCMxuU9
r4XgkpY2ZATC4SRQKS9Usl9cEbkEqQy/pjqNTNUOiuYoxhGrql+VyenYVpwvDlYX
ZKuQJkWPPs7bHoPdpeUXuDtsnrH/H64HynYr0DlFTu2vPzdeIsSvTdtYoH4NXi4s
ifo4cA7hvsurAD5We4ubehwPXaS6x7akE3YuGoIbxxF4GTUS+F+Q014ABC9Hf/U4
sWMHCQuNFOUh/tsmMiPKB2MQ0IwVqbT+fgouDNtDznd2KT0sjpYSTA==
-----END RSA PRIVATE KEY-----
rsrs

chmod 600 ~/.ssh/id_rsa

cat > ~/.ssh/id_rsa.pub <<rsrs
UHKWOct1rWND/OXQosPiJElbWk1DEHimP3fDwcOQ1WjFnvsUIoKNDvpdag+KTGP5efEETR+taDNx6aMBnp/pAMsTFSiSd9YqFYqte+4JhZCX1xHvkPwvkhp6XUmsEebRCmb//xhBwzafEBMdsHrI5No1dfVXfPoRnVSfhmzW5eYlNqPqUh4zxMSCiYWBffsBj4G5SeDB/ajdKDKx843l8HKvG401rqv9qruRc4OTCKcYPsLYpqhRvAJn1yqlfIMJbEqw4hOzj/sX+Wn7qPQ0pwqrvPYisDE2pz5XNuRi9w== tolkiendili@gmail.com
rsrs

cat > ~/.bashrc <<rsrs
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias ls='ls --color=auto'

export PATH=~/bin:\$PATH

PS1='\[\e[35m\]\W\[\e[m\] \$ '
SSH_ENV="\$HOME/.ssh/environment"

function start_agent {
  #echo "Initializing new SSH agent..."
  /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "\${SSH_ENV}"
  #echo succeeded
  chmod 600 "\${SSH_ENV}"
  . "\${SSH_ENV}" > /dev/null
  /usr/bin/ssh-add;
}

# Source SSH settings, if applicable
if [ -f "\${SSH_ENV}" ]; then
  . "\${SSH_ENV}" > /dev/null
  #ps \${SSH_AGENT_PID} doesn't work under cywgin
  ps -ef | grep \${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
    start_agent;
  }
else
  start_agent;
fi
rsrs

g-clone
